#! /bin/bash

for file in $(ls *.h) $(ls *.c)
do
	ci $file
done

for file in $(ls *.h,v) $(ls *.c,v)
do
	co $file
done

if ( make )
then
	read -n1 -p "Compilation succesful. Do you want to run it(y/n)?" rs
	
	if [ $rs == y ]
	then
		./mdc
		read
	fi
else
	echo "Compilation failed. Check the issue regarding this. "
fi

read -n1 -p "Do you want further changes and improvements?" iac
	
if [ $iac == y ]
then
	for file in $(ls *.h) $(ls *.c)
	do
		co -l $file
	done
fi


